apiVersion: v1
imagePullSecrets:
  - name: tekton-operator-dockercfg-jt7bd
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"tekton-operator","namespace":"tekton-pipelines"}}
  creationTimestamp: '2019-09-04T15:37:15Z'
  name: tekton-operator
  namespace: tekton-pipelines
  resourceVersion: '38879516'
  selfLink: /api/v1/namespaces/tekton-pipelines/serviceaccounts/tekton-operator
  uid: df1bdedb-cf29-11e9-9585-06fdbb47cfe6
secrets:
  - name: tekton-operator-dockercfg-jt7bd
  - name: tekton-operator-token-9hk9r

--
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-edit-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: tekton-aggregate-edit
  apiGroup: rbac.authorization.k8s.io