apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: java-spring-boot2-test-build-deploy-pipeline-pullrequest-binding
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: contenttype
    value: $(header.Content-Type)